name: MLFlow

on: push

jobs:
  run:
    name: Run MLFlow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
      - name: install mlflow
        run: pip install mlflow
      - name: run mlflow
        run: mlflow run .
