name: MLFlow

on: push

jobs:
  run:
    name: Run MLFlow
    runs-on: ubuntu-latest
    container: continuumio/miniconda3
    defaults:
      run:
        shell: bash -el {0}
#     strategy:
#       matrix:
#         Step: [download,preprocess,check_data,segregate,random_forest,evaluate]
    steps:
      - uses: actions/checkout@v2
#       - uses: conda-incubator/setup-miniconda@v2
#         with:
#           auto-activate-base: true
#           activate-environment: ""
#           use-only-tar-bz2: true
#       - name: source conda
#         shell: bash -el {0}
#         run: source "/usr/share/miniconda/etc/profile.d/conda.sh"
      - name: run mlflow
        run: |
          conda activate base
          pip install mlflow wandb
          wandb login ${{ secrets.WANDB_API_KEY }}
          mlflow run .
