name: MLFlow

on: push

jobs:
  run:
    name: Run MLFlow
    runs-on: ubuntu-latest
    container: continuumio/miniconda3
#     strategy:
#       matrix:
#         Step: [download,preprocess,check_data,segregate,random_forest,evaluate]
    steps:
      - uses: actions/checkout@v2
#       - uses: conda-incubator/setup-miniconda@v2
#         with:
#           auto-activate-base: true
#           activate-environment: ""
#           use-only-tar-bz2: true
#       - name: source conda
#         shell: bash -el {0}
#         run: source "/usr/share/miniconda/etc/profile.d/conda.sh"
      - name: install mlflow
        shell: bash -el {0}
        run: conda install mlflow wandb
      - name: run mlflow
        shell: bash -el {0}
        run: mlflow run . # -P "main.execute_steps='${{matrix.Step}}'"
        continue-on-error: true
